---
version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/pkg/api/"
      - "/testing/"
    schedule:
      interval: "daily"
    labels:
      - automation
      - dependency
      - Team:Elastic-Agent-Control-Plane
    open-pull-requests-limit: 10
    groups:
      elastic-apm:
        patterns:
          - "go.elastic.co/apm/*"

  # GitHub actions
  - package-ecosystem: github-actions
    directories:
      - '/'
    reviewers:
      - "elastic/observablt-ci"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"
