---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automation
      - skip-changelog
      - Team:Fleet
    allow:
      # Only update internal dependencies for now while we evaluate this workflow.
      - dependency-name: "github.com/elastic/*"
    reviewers:
      - "elastic/fleet"
    open-pull-requests-limit: 10
