---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automation
      - dependency
      - Team:Fleet
    allow:
      # Only update internal dependencies for now while we evaluate this workflow.
      - dependency-name: "github.com/elastic/*"
      - dependency-name: "go.elastic.co/*"
    reviewers:
      - "elastic/fleet"
    open-pull-requests-limit: 10
    groups:
      elastic-apm:
        patterns:
          - "go.elastic.co/apm/*"

  # GitHub actions
  - package-ecosystem: github-actions
    directories:
      - '/'
    reviewers:
      - "elastic/observablt-ci"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"
