version: "2"
run:
  go: 1.24.1
  build-tags:
    - integration
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - forbidigo
    - gocheckcompilerdirectives
    - goconst
    - gomoddirectives
    - gomodguard
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    forbidigo:
      forbid:
        - pattern: fmt.Print.*
      exclude-godoc-examples: true
    goconst:
      min-len: 3
      min-occurrences: 2
    gomoddirectives:
      replace-allow-list:
        - github.com/deepmap/oapi-codegen
      replace-local: false
    gomodguard:
      blocked:
        modules:
          - github.com/bytedance/sonic:
              reason: Federal restriction on bytedance
          - github.com/elastic/beats/v7:
              reason: There must be no Beats dependency, use elastic-agent-libs instead.
          - github.com/elastic/beats/elastic-agent:
              reason: There must be no elastic-agent dependency, use elastic-agent-libs instead.
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
        - ECS
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
