queue_rules:
  - name: default
    conditions:
      - check-success=fleet-server/pr-merge

pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - -merged
      - -closed
      - conflict
      - -author=apmmachine
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: close automated pull requests with bump updates if any conflict
    conditions:
      - -merged
      - -closed
      - conflict
      - author=apmmachine
      - label=automation
    actions:
      close:
        message: |
          This pull request has been automatically closed by Mergify.
          There are some other up-to-date pull requests.
  - name: backport patches to 7.17 branch
    conditions:
      - merged
      - base=main
      - label=backport-v7.17.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.17"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: remove backport-skip label
    conditions:
      - label~=backport-v
    actions:
      label:
        remove:
          - backport-skip
  - name: notify the backport has not been merged yet
    conditions:
      - -merged
      - -closed
      - author=mergify[bot]
      - "#check-success>0"
      - schedule=Mon-Mon 06:00-10:00[Europe/Paris]
      - "#assignee>=1"
    actions:
      comment:
        message: |
          This pull request has not been merged yet. Could you please review and merge it @{{ assignee | join(', @') }}? 🙏
  - name: automatic merge for 7\. or 8\. branches when CI passes
    conditions:
      - check-success=fleet-server/pr-merge
      - check-success=CLA
      - base~=^(7|8)\.
      - label=backport
      - author=mergify[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving mergify
      queue:
        method: squash
        name: default
  - name: automatic merge when CI passes and the file dev-tools/integration/.env is modified.
    conditions:
      - check-success=fleet-server/pr-merge
      - label=automation
      - files~=^dev-tools/integration/.env$
    actions:
      review:
        type: APPROVE
        message: Automatically approving mergify
      queue:
        method: squash
        name: default
  - name: delete upstream branch with changes on dev-tools/integration/.env or .go-version after merging/closing it
    conditions:
      - or:
        - merged
        - closed
      - and:
        - label=automation
        - head~=^updatecli.*
        - files~=^(dev-tools/integration/.env|.go-version)$
    actions:
      delete_head_branch:
  - name: backport patches to 8.6 branch
    conditions:
      - merged
      - label=backport-v8.6.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.6"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.7 branch
    conditions:
      - merged
      - label=backport-v8.7.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.7"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.8 branch
    conditions:
      - merged
      - label=backport-v8.8.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.8"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
