queue_rules:
  - name: default
    merge_method: squash
    conditions:
      - check-success=fleet-server/pr-merge

pull_request_rules:
  - name: forward-port patches to main branch
    conditions:
      - merged
      - label=forwardport-main
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "main"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: ask to resolve conflict
    conditions:
      - -merged
      - -closed
      - conflict
      - -author=apmmachine
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: close automated pull requests with bump updates if any conflict
    conditions:
      - -merged
      - -closed
      - conflict
      - author=apmmachine
      - label=automation
    actions:
      close:
        message: |
          This pull request has been automatically closed by Mergify.
          There are some other up-to-date pull requests.
  - name: backport patches to 7.17 branch
    conditions:
      - merged
      - base=main
      - label~=^(backport-v7.17.0|backport-7.17)$
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.17"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: notify the backport has not been merged yet
    conditions:
      - -merged
      - -closed
      - author=mergify[bot]
      - "#check-success>0"
      - schedule=Mon-Mon 06:00-10:00[Europe/Paris]
      - "#assignee>=1"
    actions:
      comment:
        message: |
          This pull request has not been merged yet. Could you please review and merge it @{{ assignee | join(', @') }}? 🙏
  - name: automatic merge for 7\. or 8\. branches when CI passes
    conditions:
      - check-success=fleet-server/pr-merge
      - check-success=CLA
      - base~=^(7|8)\.
      - label=backport
      - author=mergify[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving mergify
      queue:
        name: default
  - name: automatic merge when CI passes and the file dev-tools/integration/.env is modified.
    conditions:
      - check-success=fleet-server/pr-merge
      - label=automation
      - files~=^dev-tools/integration/.env$
    actions:
      review:
        type: APPROVE
        message: Automatically approving mergify
      queue:
        name: default
  - name: delete upstream branch with changes on dev-tools/integration/.env or .go-version after merging/closing it
    conditions:
      - or:
        - merged
        - closed
      - and:
        - label=automation
        - head~=^updatecli.*
        - files~=^(dev-tools/integration/.env|.go-version)$
    actions:
      delete_head_branch:
  - name: backport patches to 8.6 branch
    conditions:
      - merged
      - label=backport-v8.6.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.6"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.7 branch
    conditions:
      - merged
      - label=backport-v8.7.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.7"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.8 branch
    conditions:
      - merged
      - label=backport-v8.8.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.8"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.9 branch
    conditions:
      - merged
      - label=backport-v8.9.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.9"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.10 branch
    conditions:
      - merged
      - label=backport-v8.10.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.10"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.11 branch
    conditions:
      - merged
      - label=backport-v8.11.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.11"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.12 branch
    conditions:
      - merged
      - label=backport-v8.12.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.12"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.13 branch
    conditions:
      - merged
      - label=backport-v8.13.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.13"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.14 branch
    conditions:
      - merged
      - label=backport-v8.14.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.14"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.15 branch
    conditions:
      - merged
      - label~=^(backport-v8.15.0|backport-8.15)$
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.15"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.16 branch
    conditions:
      - merged
      - label~=^(backport-v8.16.0|backport-8.16)$
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.16"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: backport patches to 8.x branch
    conditions:
      - merged
      - label~=^(backport-v8.x|backport-8.x)$
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.x"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
  - name: notify the backport policy
    conditions:
      - -label~=^backport
      - base=main
      - -merged
      - -closed
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `backport-./d./d` is the label to automatically backport to the `8./d` branch. `/d` is the digit
  - name: add backport-8.x label for main only if no skipped or assigned already
    conditions:
      - -label~=^(backport-skip|backport-8.x)$
      - base=main
      - -merged
      - -closed
    actions:
      comment:
        message: |
          `backport-8.x` has been added to help with the transition to the new branch `8.x`.
          If you don't need it please use `backport-skip` label and remove the `backport-8.x` label.
      label:
        add:
          - backport-8.x
  - name: backport patches to 8.17 branch
    conditions:
      - merged
      - label=backport-8.17
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.17"
        labels:
          - "backport"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
