commands_restrictions:
  backport:
    conditions:
      - or:
        - sender-permission>=write
        - sender=github-actions[bot]
queue_rules:
  - name: default
    merge_method: squash
    conditions:
      - check-success=fleet-server/pr-merge
defaults:
  actions:
    backport:
      title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
      assignees:
        - "{{ author }}"
      labels:
        - "backport"
pull_request_rules:
  - name: forward-port patches to main branch
    conditions:
      - merged
      - label=forwardport-main
    actions:
      backport:
        branches:
          - "main"
  - name: ask to resolve conflict
    conditions:
      - -merged
      - -closed
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: close automated pull requests with bump updates if any conflict
    conditions:
      - -merged
      - -closed
      - conflict
      - author=github-actions[bot]
      - label=automation
    actions:
      close:
        message: |
          This pull request has been automatically closed by Mergify.
          There are some other up-to-date pull requests.
  - name: backport patches to 7.17 branch
    conditions:
      - merged
      - base=main
      - label~=^(backport-v7.17.0|backport-7.17)$
    actions:
      backport:
        branches:
          - "7.17"
  - name: notify the backport has not been merged yet
    conditions:
      - -merged
      - -closed
      - author=mergify[bot]
      - "#check-success>0"
      - schedule=Mon-Mon 06:00-10:00[Europe/Paris]
      - "#assignee>=1"
    actions:
      comment:
        message: |
          This pull request has not been merged yet. Could you please review and merge it @{{ assignee | join(', @') }}? 🙏
  - name: automatic merge for 7\. or 8\. branches when CI passes
    conditions:
      - check-success=fleet-server/pr-merge
      - check-success=CLA
      - base~=^(7|8)\.
      - label=backport
      - author=mergify[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving mergify
      queue:
        name: default
  - name: automatic merge when CI passes and the file dev-tools/integration/.env is modified.
    conditions:
      - check-success=fleet-server/pr-merge
      - label=automation
      - files~=^dev-tools/integration/.env$
    actions:
      review:
        type: APPROVE
        message: Automatically approving mergify
      queue:
        name: default
  - name: delete upstream branch with changes on dev-tools/integration/.env or .go-version after merging/closing it
    conditions:
      - or:
        - merged
        - closed
      - and:
        - label=automation
        - head~=^updatecli.*
        - files~=^(dev-tools/integration/.env|.go-version)$
    actions:
      delete_head_branch:
  - name: backport patches to 8.6 branch
    conditions:
      - merged
      - label=backport-v8.6.0
    actions:
      backport:
        branches:
          - "8.6"
  - name: backport patches to 8.7 branch
    conditions:
      - merged
      - label=backport-v8.7.0
    actions:
      backport:
        branches:
          - "8.7"
  - name: backport patches to 8.8 branch
    conditions:
      - merged
      - label=backport-v8.8.0
    actions:
      backport:
        branches:
          - "8.8"
  - name: backport patches to 8.9 branch
    conditions:
      - merged
      - label=backport-v8.9.0
    actions:
      backport:
        branches:
          - "8.9"
  - name: backport patches to 8.10 branch
    conditions:
      - merged
      - label=backport-v8.10.0
    actions:
      backport:
        branches:
          - "8.10"
  - name: backport patches to 8.11 branch
    conditions:
      - merged
      - label=backport-v8.11.0
    actions:
      backport:
        branches:
          - "8.11"
  - name: backport patches to 8.12 branch
    conditions:
      - merged
      - label=backport-v8.12.0
    actions:
      backport:
        branches:
          - "8.12"
  - name: backport patches to 8.13 branch
    conditions:
      - merged
      - label=backport-v8.13.0
    actions:
      backport:
        branches:
          - "8.13"
  - name: backport patches to 8.14 branch
    conditions:
      - merged
      - label=backport-v8.14.0
    actions:
      backport:
        branches:
          - "8.14"
  - name: backport patches to 8.15 branch
    conditions:
      - merged
      - label~=^(backport-v8.15.0|backport-8.15)$
    actions:
      backport:
        branches:
          - "8.15"
  - name: backport patches to 8.16 branch
    conditions:
      - merged
      - label~=^(backport-v8.16.0|backport-8.16)$
    actions:
      backport:
        branches:
          - "8.16"
  - name: notify the backport policy
    conditions:
      - -label~=^backport
      - base=main
      - -merged
      - -closed
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `backport-./d./d` is the label to automatically backport to the `8./d` branch. `/d` is the digit
          * `backport-active-all` is the label that automatically backports to all active branches.
          * `backport-active-8` is the label that automatically backports to all active minor branches for the 8 major.
          * `backport-active-9` is the label that automatically backports to all active minor branches for the 9 major.
  - name: backport patches to 8.17 branch
    conditions:
      - merged
      - label=backport-8.17
    actions:
      backport:
        branches:
          - "8.17"
  - name: backport patches to 8.18 branch
    conditions:
      - merged
      - label=backport-8.18
    actions:
      backport:
        branches:
          - "8.18"
  - name: backport patches to 8.19 branch
    conditions:
      - merged
      - label=backport-8.19
    actions:
      backport:
        branches:
          - "8.19"
  - name: backport patches to 9.0 branch
    conditions:
      - merged
      - label=backport-9.0
    actions:
      backport:
        branches:
          - "9.0"
  - name: backport patches to 9.1 branch
    conditions:
      - merged
      - label=backport-9.1
    actions:
      backport:
        branches:
          - "9.1"
  - name: backport patches to 9.2 branch
    conditions:
      - merged
      - label=backport-9.2
    actions:
      backport:
        branches:
          - "9.2"
