pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? ðŸ™
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: backport patches to 7.x branch
    conditions:
      - base=master
      - label=v7.13.0
    actions:
      backport:
        branches:
          - "7.x"
  - name: backport patches to 7.12 branch
    conditions:
      - base=master
      - label=v7.12.0
    actions:
      backport:
        branches:
          - "7.12"
  - name: automatic merge for 7.x when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=fleet-server/pr-merge
      - check-success=CLA
      - base=7.x
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        priority: low
  - name: automatic merge for 7.12 when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=fleet-server/pr-merge
      - check-success=CLA
      - base=7.12
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        priority: low
