pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: backport patches to 7.x branch
    conditions:
      - merged
      - base=master
      - label=v7.14.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.x"
        labels:
          - "backport"
  - name: backport patches to 7.13 branch
    conditions:
      - merged
      - base=master
      - label=v7.13.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.13"
        labels:
          - "backport"
  - name: backport patches to 7.12 branch
    conditions:
      - merged
      - base=master
      - label=v7.12.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.12"
        labels:
          - "backport"
  - name: automatic merge for 7.x when CI passes
    conditions:
      - check-success=fleet-server/pr-merge
      - check-success=CLA
      - base=7.x
      - label=backport
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: automatic merge for 7.13 when CI passes
    conditions:
      - check-success=fleet-server/pr-merge
      - check-success=CLA
      - base=7.13
      - label=backport
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: automatic merge for 7.12 when CI passes
    conditions:
      - check-success=fleet-server/pr-merge
      - check-success=CLA
      - base=7.12
      - label=backport
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
