# Declare a Backstage Component that represents your application.
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fleet-server
  description: fleet-server - The control server for managing a fleet of elastic-agents

spec:
  type: tool
  owner: group:ingest-fp
  system: platform-ingest
  lifecycle: production
  dependsOn:
    - "component:package-registry"
    - "resource:buildkite-pipeline-release-package-registry-distribution"


---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-fleet-server
  description: Buildkite pipeline for the Elastic Fleet Server project
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/fleet-server

spec:
  type: buildkite-pipeline
  owner: group:ingest-fp
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: fleet-server
      description: Buildkite pipeline for the Elastic Fleet Server project
    spec:
      repository: elastic/fleet-server
      pipeline_file: ".buildkite/pipeline.yml"
      branch_configuration: "main 8.* 7.* v8.* v7.*"
      provider_settings:
        build_pull_request_forks: false
        build_pull_requests: true # requires filter_enabled and filter_condition settings as below when used with buildkite-pr-bot
        build_tags: true
        filter_enabled: true
        filter_condition: >-
          build.pull_request.id == null || (build.creator.name == 'elasticmachine' && build.pull_request.id != null)
      teams:
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-fleet-server-package-mbp
  description: Buildkite pipeline for the Elastic Fleet Server package process
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/fleet-server-package-mbp

spec:
  type: buildkite-pipeline
  owner: group:ingest-fp
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: fleet-server-package-mbp
      description: Buildkite pipeline for the Elastic Fleet Server package process
    spec:
      repository: elastic/fleet-server
      pipeline_file: ".buildkite/pipeline.package.mbp.yml"
      provider_settings:
        build_pull_request_forks: false
        build_pull_requests: true
        build_tags: false
        build_branches: false
        filter_enabled: true
        filter_condition: >-
          build.pull_request.id == null || (build.creator.name == 'elasticmachine' && build.pull_request.id != null)
      teams:
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY