==== Breaking Changes

- Upgrade to Go 1.18. Certificates signed with SHA-1 are now rejected. See the Go 1.18 https://tip.golang.org/doc/go1.18#sha1[release notes] for details. {pull}1709[1709]

==== Bugfixes

- Return a better error on enrolling and the Elasticsearch version is incompatible. {pull}1211[1211]
- Give a grace period when starting the unenroll monitor. {issue}1500[1500]
- Fixes a race condition between the unenroller goroutine and the main goroutine for the coordinator monitor. {issues}1738[1738]
- Remove events from agent checkin body. {issue}1774[1774]
- Improve authc debug logging. {pull}1870[1870]
- Add error detail to catch-all HTTP error response. {pull}1854[1854]
- Fix issue were errors where being ignored written to elasticsearch. {pull}1896[1896]
- LoadServerLimits will not overwrite specified limits when loading default/agent number specified values. {issue}1841[1841] {pull}1912[1912]
- Use seperate rate limiters for internal and external API listeners. {issue}1859[1859] {pull}1904[1904]
- Update apikey.cache_hit log field name to match convention. {pull}1900[1900]
- Fix fleet.migration.total log key overlap {pull}1951[1951]

==== New Features

- Fleet server now supports Logstash type outputs for managed agents. {pull}1188[1188]
- Use the darwin-aarch64 as the suffix for Darwin Arm64 release {pull}1267[1267]
- Allow Elastic Agent to provide tags at enrollment time to identify them. {pull}1350[1350]
- Add start_time and minimum_execution_duration to actions to allow fleet-server to schedule agent actions. {pull}1381[1381]
- Fleet Server now allows setting global labels on APM instrumentation. {pull}1649[1649]
- Fleet Server now allows setting transaction sample rate on APM instrumentation {pull}1681[1681]
- Log redacted config when config updates. {issue}1626[1626] {pull}1668[1668]
