ARG GO_VERSION
FROM docker.elastic.co/beats-dev/golang-crossbuild:${GO_VERSION}-main-debian11

RUN \
  apt-get update \
  && apt-get install -y zip \
  && mkdir -p /.cache \
  && chmod 777 /.cache

WORKDIR /go/src/github.com/elastic/fleet-server

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

ENTRYPOINT [ "make" ]
CMD [ "release" ]
