ARG GO_VERSION
FROM golang:${GO_VERSION}-bullseye

RUN \
  apt-get update \
  && apt-get install --no-install-recommends -y zip \
  && apt-get clean

WORKDIR /go/src/github.com/elastic/fleet-server

ENTRYPOINT [ "make", "release" ]
