// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by dev-tools/cmd/buildlimits/buildlimits.go - DO NOT EDIT.

package config

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestLoadLimits(t *testing.T) {
	testCases := []struct {
		Name           string
		CurrentRAM     int
		ExpectedMaxRAM int
	}{
		{"low ram", 128, 512},
		{"precise", 512, 512},
		{"in the middle", 650, 1024},
		{"2-to-4", 2650, 4096},
		{"close to max", 8000, 8192},
		{"above max", 9203, 17179869184},
	}

	for _, tc := range testCases {
		t.Run(tc.Name, func(t *testing.T) {
			l := loadLimitsForRam(tc.CurrentRAM)

			require.Equal(t, tc.ExpectedMaxRAM, l.MaxRAM)
		})
	}
}
