// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by dev-tools/cmd/buildlimits/buildlimits.go - DO NOT EDIT.

package config

import (
	"math"
	"runtime"
	"strings"
	"time"

	"github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/packer"
	"github.com/elastic/go-ucfg/yaml"
	"github.com/pbnjay/memory"
	"github.com/pkg/errors"
	"github.com/rs/zerolog/log"
)

const (
	defaultCacheNumCounters = 500000           // 10x times expected count
	defaultCacheMaxCost     = 50 * 1024 * 1024 // 50MiB cache size

	defaultMaxConnections = 0 // no limit
	defaultPolicyThrottle = time.Millisecond * 5

	defaultCheckinInterval = time.Millisecond
	defaultCheckinBurst    = 1000
	defaultCheckinMax      = 0
	defaultCheckinMaxBody  = 1024 * 1024

	defaultArtifactInterval = time.Millisecond * 5
	defaultArtifactBurst    = 25
	defaultArtifactMax      = 50
	defaultArtifactMaxBody  = 0

	defaultEnrollInterval = time.Millisecond * 10
	defaultEnrollBurst    = 100
	defaultEnrollMax      = 50
	defaultEnrollMaxBody  = 1024 * 512

	defaultAckInterval = time.Millisecond * 10
	defaultAckBurst    = 100
	defaultAckMax      = 50
	defaultAckMaxBody  = 1024 * 1024 * 2

	defaultStatusInterval = time.Millisecond * 5
	defaultStatusBurst    = 25
	defaultStatusMax      = 50
	defaultStatusMaxBody  = 0
)

type valueRange struct {
	Min int `config:"min"`
	Max int `config:"max"`
}

type envLimits struct {
	Agents         valueRange           `config:"num_agents"`
	RecommendedRAM int                  `config:"recommended_min_ram"`
	Server         *serverLimitDefaults `config:"server_limits"`
	Cache          *cacheLimits         `config:"cache_limits"`
}

func defaultEnvLimits() *envLimits {
	return &envLimits{
		Agents: valueRange{
			Min: 0,
			Max: int(getMaxInt()),
		},
		Server: defaultserverLimitDefaults(),
		Cache:  defaultCacheLimits(),
	}
}

type cacheLimits struct {
	NumCounters int64 `config:"num_counters"`
	MaxCost     int64 `config:"max_cost"`
}

func defaultCacheLimits() *cacheLimits {
	return &cacheLimits{
		NumCounters: defaultCacheNumCounters,
		MaxCost:     defaultCacheMaxCost,
	}
}

type limit struct {
	Interval time.Duration `config:"interval"`
	Burst    int           `config:"burst"`
	Max      int64         `config:"max"`
	MaxBody  int64         `config:"max_body_byte_size"`
}

type serverLimitDefaults struct {
	PolicyThrottle time.Duration `config:"policy_throttle"`
	MaxConnections int           `config:"max_connections"`

	CheckinLimit  limit `config:"checkin_limit"`
	ArtifactLimit limit `config:"artifact_limit"`
	EnrollLimit   limit `config:"enroll_limit"`
	AckLimit      limit `config:"ack_limit"`
	StatusLimit   limit `config:"status_limit"`
}

func defaultserverLimitDefaults() *serverLimitDefaults {
	return &serverLimitDefaults{
		PolicyThrottle: defaultCacheNumCounters,
		MaxConnections: defaultCacheMaxCost,

		CheckinLimit: limit{
			Interval: defaultCheckinInterval,
			Burst:    defaultCheckinBurst,
			Max:      defaultCheckinMax,
			MaxBody:  defaultCheckinMaxBody,
		},
		ArtifactLimit: limit{
			Interval: defaultArtifactInterval,
			Burst:    defaultArtifactBurst,
			Max:      defaultArtifactMax,
			MaxBody:  defaultArtifactMaxBody,
		},
		EnrollLimit: limit{
			Interval: defaultEnrollInterval,
			Burst:    defaultEnrollBurst,
			Max:      defaultEnrollMax,
			MaxBody:  defaultEnrollMaxBody,
		},
		AckLimit: limit{
			Interval: defaultAckInterval,
			Burst:    defaultAckBurst,
			Max:      defaultAckMax,
			MaxBody:  defaultAckMaxBody,
		},
		StatusLimit: limit{
			Interval: defaultStatusInterval,
			Burst:    defaultStatusBurst,
			Max:      defaultStatusMax,
			MaxBody:  defaultStatusMaxBody,
		},
	}
}

var defaults []*envLimits

func init() {
	// Packed Files
	// internal/pkg/config/defaults/gt10000_limits.yml
	// internal/pkg/config/defaults/gt12500_limits.yml
	// internal/pkg/config/defaults/gt5000_limits.yml
	// internal/pkg/config/defaults/gt50_limits.yml
	// internal/pkg/config/defaults/gt7500_limits.yml
	// internal/pkg/config/defaults/lte50_limits.yml
	// internal/pkg/config/defaults/max_limits.yml
	unpacked := packer.MustUnpack("eJzsl0+PqzYUxff9GLOuOkBCqlR6C08IDIxMFAQY2FQYJgTG/NELhD9Vv3tlSNJMwgRQKz2p6jJSOL4+9+dz7T+ewiR//5645Dn7CJ69NNmFwbP/vnMLkh+eg5xlGIb5nYRxmB9+qWPy9NsTTszc4sTEQTzjNembvHrJXTRfyMK6hAIoVyEIMBLnmxBUMDJKCLLaQeoRI5bgWCOOuMxdxO+8WMw3IZhD/aNexere5vbE4qoMI3LWLXzE7mxuyeJEI14C6RocXQOCNJAldv8uLiM8U5lNCGoofMygbtRQAG8eZ9Z+bNY3eiXmqsyekZ0v7Ws80xgsGQtZMHOvvNLj+MJBKuOiZeE1aQAbme6Lfh+5khm5HCnOupsgDeQVCFzEM46lcDYqF7JglPDVbKgP8uol9C2l8YU0UM91r2782dK1xdqXSGwjlbloh3RNEMgSKXyJ7kc8bELAQuGFbetdgcBOzNqbbReysD3VCLp9CGmwufhkFl68PGBxeXARm9FaTrVlna/OHgtpAPWX/F53fVtzffJib3P5Dkskd63tok9P1UHpW/BUk8J6Sdsn5swI5ca2goUsBLT2b08/D8LI8RNgrGkBVzA2HTgPYazUCM5VkEU2UlPHPBn2CtsNdmupR79rdtP9H5zhyG1rT2Ftmw0jwKvNmoURKFeJSk0hHvms50n0t8pbMy314iXjSxWhBuPWtItegWMz8iVyxO0BgPXZQHpgbC7PMLk09h8BA3WjhMK6ba6XaJkTi5E/AM3EJlNtghPliKXqAo8M+g7RusT3utVdzdHJC6R+/5cO5ZzWPgwjPyEYjStGqBce24ZUbEaYY3MH8R8O0nYYkcKaKXust/tiNuM5ZL4IRfYSiiBrqBeOpZx815rWp9eXI5ZI9G4uGfdVOfqv2sHRr8Lgq1DUwcRQVPrD5aafajM5EOsvOLnhT/7B/I3bP9WD4NuIMOQn0HeVgmzrTKIQm1vmGJmFI5kfFsfSFKltxHRVRds3mxNpZz/TIvEsNildZtuBloThBJw4jo3ycQJ6E8kze5w3bk899aVqO2kpjIucvT3TBggZpXsh0UF8jbnqMEQzlNj7lNJvk3osddroGoeJ+3XC9O0S7u/Td7oaPuRuW250ezR37fWmjzsdMBvBmKnTJy/7mDu5nDh5q54Eqe+TqfVmIntiT1/l+zT9wVdAiO5Z7hLukx4zhj+Sv4+JvM5SYwA1MC3eHrw2pl7uoDA8WCdd7nriAkZGf1yMxmtd9urex9CkgdobbdubKGq9FiOXfXy0+vd9N0wHB2nsVmMzDY7IMFirjT0f/5ztbvP/keds++L6/zl7es7++dNfAQAA//+AxNVZ")

	for f, v := range unpacked {
		cfg, err := yaml.NewConfig(v, DefaultOptions...)
		if err != nil {
			panic(errors.Wrap(err, "Cannot read spec from "+f))
		}

		l := defaultEnvLimits()
		if err := cfg.Unpack(&l, DefaultOptions...); err != nil {
			panic(errors.Wrap(err, "Cannot unpack spec from "+f))
		}

		defaults = append(defaults, l)
	}
}

func loadLimits(agentLimit int) *envLimits {
	return loadLimitsForAgents(agentLimit)
}

func loadLimitsForAgents(agentLimit int) *envLimits {
	for _, l := range defaults {
		// get nearest limits for configured agent numbers
		if l.Agents.Min < agentLimit && agentLimit <= l.Agents.Max {
			log.Info().Msgf("Using system limits for %d to %d agents for a configured value of %d agents", l.Agents.Min, l.Agents.Max, agentLimit)
			ramSize := int(memory.TotalMemory() / 1024 / 1024)
			if ramSize < l.RecommendedRAM {
				log.Warn().Msgf("Detected %d MB of system RAM, which is lower than the recommended amount (%d MB) for the configured agent limit", ramSize, l.RecommendedRAM)
			}
			return l
		}
	}
	log.Info().Msgf("No applicable limit for %d agents, using default.", agentLimit)
	return defaultEnvLimits()
}

func getMaxInt() int64 {
	if strings.HasSuffix(runtime.GOARCH, "64") {
		return math.MaxInt64
	}
	return math.MaxInt32
}
