max_ram: 4096
cache_limits:
  num_counters: 80000
  max_cost: 104857600
server_limits:
  policy_throttle: 5ms
  max_connections: 20000
  checkin_limit:
    interval: 1ms
    burst: 2000
    max: 10001
  artifact_limit: 
    interval: 1ms
    burst: 2000
    max: 4000
  enroll_limit: 
    interval: 10ms
    burst: 100
    max: 200
  ack_limit:
    interval: 1ms
    burst: 2000
    max: 4000