num_agents:
  min: 50000
  max: 99999
recommended_min_ram: 32768
cache_limits:
  num_counters: 640000
  max_cost: 419430400
server_limits:
  policy_throttle: 2ms
  max_connections: 32000
  checkin_limit:
    interval: 250us
    burst: 8000
    max: 55000
  artifact_limit: 
    interval: 250us
    burst: 8000
    max: 16000
  enroll_limit: 
    interval: 10ms
    burst: 200
    max: 400
  ack_limit:
    interval: 250us
    burst: 8000
    max: 16000
