num_agents:
  min: 5000
  max: 7500
recommended_min_ram: 2048
cache_limits:
  num_counters: 40000
  max_cost: 50971520
server_limits:
  policy_throttle: 10ms
  max_connections: 10000
  checkin_limit:
    interval: 2ms
    burst: 1000
    max: 7501
  artifact_limit: 
    interval: 2ms
    burst: 1000
    max: 2000
  enroll_limit: 
    interval: 10ms
    burst: 100
    max: 200
  ack_limit:
    interval: 2ms
    burst: 1000
    max: 2000