num_agents:
  max: 50
recommended_min_ram: 0
cache_limits:
  num_counters: 2000
  max_cost: 2097152
server_limits:
  policy_throttle: 200ms
  max_connections: 100
  checkin_limit:
    interval: 50ms
    burst: 25
    max: 100
  artifact_limit: 
    interval: 100ms
    burst: 10
    max: 10
  enroll_limit: 
    interval: 100ms
    burst: 5
    max: 10
  ack_limit:
    interval: 10ms
    burst: 20
    max: 20