num_agents:
  min: 40001
recommended_min_ram: 32384
cache_limits:
  num_counters: 6400000
  max_cost: 536870912
server_limits:
  action_limit:
    interval: 0.25ms
    burst: 1000
  checkin_limit:
    interval: 0.25ms
    burst: 8000
    max: 80000
  artifact_limit:
    interval: 0.25ms
    burst: 8000
    max: 16000
  enroll_limit:
    interval: 10ms
    burst: 200
    max: 400
  ack_limit:
    interval: 0.25ms
    burst: 8000
    max: 16000
  status_limit:
    interval: 5ms
    burst: 200
    max: 400
  upload_start_limit:
    interval: 2s
    burst: 40
    max: 80
  upload_end_limit:
    interval: 2s
    burst: 40
    max: 80
  upload_chunk_limit:
    interval: 3ms
    burst: 40
    max: 80
  file_delivery_limit:
    interval: 100ms
    burst: 40
    max: 80
  pgp_retieval_limit:
    interval: 0.25ms
    burst: 8000
    max: 16000
