# These pipeline steps constitute the quality gate for your service within the Staging environment.
# Incorporate any necessary additional logic to validate the service's integrity. A failure in
# this pipeline build will prevent further progression to the subsequent stage.

steps:
  - command:
      - echo "Waiting for 10m for indicative health metrics"
      - sleep 600
  - wait
  - label: ":rocket: Run observability gates"
    trigger: "serverless-quality-gates"
    build:
      branch: main
      commit: HEAD
      message: "${BUILDKITE_MESSAGE}"
      env:
        TARGET_ENV: staging
        SERVICE: fleet-server
        CHECK_LOG_ERROR_RATE: true
        CHECK_CONTAINER_RESTART_COUNT: true
        CONTAINER_NAME: fleet-server
        CHECK_API_REQUEST_METRICS: true
        SERVICE_TYPE_FIELD: service.name
        SERVICE_VERSION: ${SERVICE_VERSION:0:12}