# These pipeline steps constitute the quality gate for fleet server within the production canary environment.
# A failure in this pipeline build will prevent further progression to the subsequent stage.

steps:

  - label: ":rocket: Run serverless synthetics check"
    if: build.env("ENVIRONMENT") == "production-canary"
    trigger: "serverless-quality-gates"
    build:
      message: "${BUILDKITE_MESSAGE} (triggered by pipeline.tests-production-canary.yaml)"
      env:
        TARGET_ENV: production
        SERVICE: fleet
        CHECK_SYNTHETICS: true
        CHECK_SYNTHETICS_TAG: serverless-platform-core-validation

  - label: ":cookie: 1h bake period before continuing promotion"
    if: build.env("ENVIRONMENT") == "production-canary"
    command: "sleep 3600"
