steps:
  - group: "Run tests"
    key: "tests"
    steps:
      - label: "E2E Test"
        key: "e2e-test"
        command: ".buildkite/scripts/e2e_test.sh"
        agents:
          provider: "gcp"
        depends_on:
          - step: "unit-test"
            allow_failure: false
          - step: "int-test"
            allow_failure: false

notify:
  - slack: "#fleet-cloud-services"
    if: build.state == "failed"

env:
  SETUP_GVM_VERSION: 'v0.5.0'
  DOCKER_COMPOSE_VERSION: '1.25.5'
  DOCKER_REGISTRY: "docker.elastic.co"
  DOCKER_IMAGE: "${DOCKER_REGISTRY}/observability-ci/temp-fleet-server" # needs to rename after tests
  DOCKER_IMAGE_SHA_TAG: "temp-${BUILDKITE_COMMIT}" # needs to rename after tests
  DOCKER_IMAGE_LATEST_TAG: "temp-latest" # needs to rename after tests
  DOCKER_IMAGE_GIT_TAG: "temp-${BUILDKITE_BRANCH}" # needs to rename after tests
  GO_AGENT_IMAGE: "golang:1.20.3"
  TERRAFORM_VERSION: '1.4.6'
  JOB_GCS_BUCKET: 'fleet-ci-artifacts'