name: "fleet server package mbp"
steps:
  - label: ":pipeline: test step"
    command: echo "test-pipeline"

  - group: "test group"
    steps:
      - label: "step1 of the group"
        command: echo "step1 of the group"

      - label: "step2 of the group"
        command: echo "step2 of the group"