# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  DOCKER_COMPOSE_VERSION: "1.25.5"
  TERRAFORM_VERSION: "1.6.4"

steps:

  - label: "Validate catalog-info"
    if: build.pull_request.id != null
    plugins:
      monorepo-diff#v1.3.0:
        diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
        wait: true
        watch:
          # if our catalog-info.yaml is changed, make sure it's well-formed according to our internal standards as well as Backstage's validation
          - path: "catalog-info.yaml"
            config:
              command: "/agent/check-catalog-info.sh"
              agents:
                image: "docker.elastic.co/ci-agent-images/pipelib:0.13.0@sha256:190464950de81cb3390bd5e07bb1cc171dd4a765c1ce5de58ebca476f9a6839f"

  - group: "Check and build"
    key: "check"
    steps:
      - label: ":white_check_mark: Run check-ci"
        key: check-ci
        command: ".buildkite/scripts/check_ci.sh"
        agents:
          provider: "gcp"

      - label: ":building_construction: Run local build"
        key: make-local
        command: ".buildkite/scripts/local_build.sh"
        agents:
          provider: "gcp"

      - label: ":building_construction: Run local build: MacOS"
        key: make-local-macos
        command: ".buildkite/scripts/local_build.sh"
        agents:
          provider: orka
          imagePrefix: generic-13-ventura-arm

  - group: "Performance test"
    key: "performance-test"
    depends_on: "check"
    steps:
      - label: "Run go benchmark for PR branch"
        key: "go-benchmark-pr"
        command: ".buildkite/scripts/run_benchmark.sh pr"
        env:
          BENCHMARK_ARGS: "-count=8 -benchmem"
        artifact_paths:
          - build/next.out
          - build/next.stat
        agents:
          provider: "gcp"
          machineType: "c2-standard-8"

      - label: "Run go benchmark for ${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        key: "go-benchmark-base"
        command: ".buildkite/scripts/run_benchmark.sh base"
        env:
          BENCHMARK_ARGS: "-count=8 -benchmem"
        artifact_paths:
          - build/base.out
          - build/base.stat
        agents:
          provider: "gcp"
          machineType: "c2-standard-8"

      - label: "Compare results"
        key: "go-benchmark-compare"
        command: ".buildkite/scripts/run_benchmark.sh compare"
        artifact_paths:
          - build/failed_summary.md
          - build/failed_report.json
          - build/full_report.json
        depends_on:
          - go-benchmark-pr
          - go-benchmark-base
        agents:
          provider: "gcp"

  - group: "Run tests"
    key: "tests"
    depends_on: "check"
    steps:
      - label: ":smartbear-testexecute: Run unit tests"
        key: unit-test
        command: ".buildkite/scripts/unit_test.sh"
        agents:
          provider: "gcp"
        artifact_paths:
          - build/*.xml
          - build/coverage*.out

      - label: ":smartbear-testexecute: Run unit tests with requirefips build tag"
        key: unit-test-fips-tag
        command: ".buildkite/scripts/unit_test.sh"
        env:
          FIPS: "true"
        agents:
          provider: "gcp"
        artifact_paths:
          - build/*.xml
          - build/coverage*.out

      - label: ":smartbear-testexecute: Run fips140=only unit tests"
        key: unit-test-fips140-only
        command: ".buildkite/scripts/unit_test_fipsonly.sh"
        env:
          FIPS: "true"
        agents:
          provider: "gcp"
        artifact_paths:
          - build/*.xml
          - build/coverage*.out

      - label: ":smartbear-testexecute: Run unit tests: MacOS 13"
        key: unit-test-macos-13
        command: ".buildkite/scripts/unit_test.sh"
        agents:
          provider: orka
          imagePrefix: generic-13-ventura-arm
        artifact_paths:
          - build/*.xml
          - build/coverage*.out

      - label: ":smartbear-testexecute: Run integration tests"
        key: int-test
        command: ".buildkite/scripts/integration_test.sh"
        agents:
          provider: "gcp"
        artifact_paths:
          - build/*.xml
        plugins:
          - test-collector#v1.10.2:
              files: "build/test-*.xml"
              format: "junit"
              branches: "main"
              debug: true

      - label: "E2E Test"
        key: "e2e-test"
        command: ".buildkite/scripts/e2e_test.sh"
        agents:
          provider: "gcp"
        artifact_paths:
          - build/*.xml
          - build/e2e-coverage.out
        plugins:
          - test-collector#v1.10.2:
              files: "build/test-*.xml"
              format: "junit"
              branches: "main"
              debug: true

      - label: ":junit: Junit annotate"
        plugins:
          - junit-annotate#v2.4.1:
              artifacts: "build/*.xml"
        agents:
          provider: "gcp"
        depends_on:
          - step: "unit-test"
            allow_failure: true
          - step: "unit-test-macos-13"
            allow_failure: true
          - step: "int-test"
            allow_failure: true
          - step: "e2e-test"
            allow_failure: true

      - label: ":sonarqube: Continuous Code Inspection"
        env:
          VAULT_SONAR_TOKEN_PATH: "kv/ci-shared/platform-ingest/elastic/fleet-server/sonar-analyze-token"
        agents:
          image: "docker.elastic.co/cloud-ci/sonarqube/buildkite-scanner:latest"
        command:
          - "buildkite-agent artifact download build/*coverage*.out ."
          - "buildkite-agent artifact download build/test-unit*.out.xml ."
          - "/scan-source-code.sh"
        depends_on:
          - step: "unit-test"
            allow_failure: false
          - step: "e2e-test"
            allow_failure: false
          - step: "unit-test-macos-13"
            allow_failure: false

      - label: ":gcloud: Cloud e2e Test"
        key: "cloud-e2e-test"
        env:
          DOCKER_REGISTRY: "docker.elastic.co"
          DOCKER_IMAGE: "docker.elastic.co/beats-ci/elastic-agent-cloud-fleet"
          DOCKER_IMAGE_TAG: "pr-${BUILDKITE_PULL_REQUEST}-${BUILDKITE_COMMIT:0:12}"
          SNAPSHOT: "true"
          PLATFORMS: "linux/amd64"
          TF_VAR_pull_request: "${BUILDKITE_PULL_REQUEST}"
        command: ".buildkite/scripts/cloud_e2e_test.sh"
        agents:
          provider: "gcp"
        depends_on:
          - step: "unit-test"
            allow_failure: false
          - step: "int-test"
            allow_failure: false
          - step: "e2e-test"
            allow_failure: false

      - label: ":gcloud: Cloud e2e FIPS Test"
        key: "cloud-e2e-fips-test"
        env:
          DOCKER_REGISTRY: "docker.elastic.co"
          DOCKER_BASE_IMAGE: "docker.elastic.co/cloud-release/elastic-agent-fips-cloud"
          DOCKER_IMAGE: "docker.elastic.co/beats-ci/elastic-agent-fips-cloud"
          DOCKER_IMAGE_TAG: "pr-${BUILDKITE_PULL_REQUEST}-${BUILDKITE_COMMIT:0:12}"
          SNAPSHOT: "true"
          PLATFORMS: "linux/amd64"
          TF_VAR_pull_request: "${BUILDKITE_PULL_REQUEST}"
          FIPS: "true"
        command: ".buildkite/scripts/cloud_e2e_test.sh"
        agents:
          provider: "gcp"
        depends_on:
          - step: "unit-test"
            allow_failure: false
          - step: "int-test"
            allow_failure: false
          - step: "e2e-test"
            allow_failure: false

  - label: ":docker: Publish docker image"
    key: "publish"
    command: ".buildkite/scripts/build_push_docker_image.sh"
    env:
      DOCKER_REGISTRY: "docker.elastic.co"
      DOCKER_IMAGE: "docker.elastic.co/observability-ci/fleet-server" # needs to rename for rollback
      DOCKER_IMAGE_SHA_TAG: "git-${BUILDKITE_COMMIT:0:12}" # needs to rename for rollback, should be "git-${BUILDKITE_COMMIT:0:12}"
      DOCKER_IMAGE_LATEST_TAG: "latest" # needs to rename for rollback
      DOCKER_IMAGE_GIT_TAG: "${BUILDKITE_BRANCH}" # needs to rename for rollback
    if: "build.env('BUILDKITE_PULL_REQUEST') == 'false' && build.env('BUILDKITE_BRANCH') == 'main'"
    agents:
      provider: "gcp"
    depends_on:
      - step: "tests"
        allow_failure: false

  - label: ":serverless::argo: Run synthetics tests and update fleet to ${BUILDKITE_COMMIT:0:12} in serverless-gitops"
    async: true
    branches: main
    trigger: gpctl-promote-after-serverless-devenv-synthetics
    build:
      env:
        SERVICE_COMMIT_HASH: ${BUILDKITE_COMMIT:0:12}
        SERVICE: fleet
    depends_on:
      - step: "publish"

  - label: ":gcloud: Release test"
    key: "release-test"
    command: ".buildkite/scripts/release_test.sh"
    agents:
      provider: "gcp"
    depends_on:
      - step: "tests"
        allow_failure: false
    plugins:
      # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/fleet-server/01-gcp-buildkite-oidc.tf
      # This plugin authenticates to Google Cloud using the OIDC token.
      - elastic/oblt-google-auth#v1.2.0:
          lifetime: 10800 # seconds
          project-id: "elastic-observability-ci"
          project-number: "911195782929"

  - label: ":jenkins: Release - Package Registry Distribution"
    key: "release-package-registry"
    trigger: "package-registry-release-package-registry-distribution"
    async: true
    build:
      branch: "main"
      meta_data:
        DOCKER_TAG: "${BUILDKITE_TAG}"
    if: "build.env('BUILDKITE_TAG') != ''"

  - trigger: "fleet-server-package-mbp"
    label: ":esbuild: Downstream - Package"
    key: "downstream-package"
    async: true
    if: "build.env('BUILDKITE_PULL_REQUEST') == 'false' && build.env('BUILDKITE_TAG') == '' && build.env('BUILDKITE_BRANCH') != ''"
    build:
      branch: "${BUILDKITE_BRANCH}"
    depends_on:
      - step: "release-test"
        allow_failure: false
