# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
name: "fleet server package mbp"
env:
  REPO: 'fleet-server'
  SETUP_GVM_VERSION: 'v0.3.0'
  DOCKER_REGISTRY: "docker.elastic.co"

steps:
  - group: "Package and Publish"
    key: "package-publish"
    steps:
    - label: "Package Ubuntu-20 x86_64"
      key: "package-x86-64"
      command: ".buildkite/scripts/package.sh {{matrix.type}}"
      agents:
        provider: "gcp"
        image: "family/core-ubuntu-2004"
      matrix:
        setup:
          type:
          - "snapshot"
          - "staging"

    - label: "Package Ubuntu-20 aarch64"
      key: "package-arm"
      command: ".buildkite/scripts/package.sh {{matrix.type}}"
      agents:
        provider: "aws"
        image: "core-ubuntu-2004-aarch64"
      matrix:
        setup:
          type:
          - "snapshot"
          - "staging"

  - label: "DRA snapshot"
    key: "dra-snapshot"
    command: ".buildkite/scripts/dra_release.sh snapshot"
    agents:
      provider: "gcp"
      image: "family/core-ubuntu-2004"
    if: ${IS_FILE_EXISTS_IN_REPO}
    depends_on:
      - step: "package-publish"
        allow_failure: false

  - label: "DRA release staging"
    key: "dra-staging"
    command: ".buildkite/scripts/dra_release.sh staging"
    agents:
      provider: "gcp"
      image: "family/core-ubuntu-2004"
#    if: "${IS_FILE_EXISTS_IN_REPO} == true && build.env('BUILDKITE_BRANCH') != 'main'"
    depends_on:
      - step: "rda-snapshot"
        allow_failure: false
