# These pipeline steps constitute the quality gate for fleet server within the production canary environment.
# A failure in this pipeline build will prevent further progression to the subsequent stage.

steps:
  - label: ":pipeline::rocket::seedling: Trigger control-plane e2e tests"
    trigger: "ess-k8s-production-e2e-tests" # https://buildkite.com/elastic/ess-k8s-production-e2e-tests
    build:
      env:
        REGION_ID: aws-us-east-1
        NAME_PREFIX: ci_test_kibana-promotion_
      message: "${BUILDKITE_MESSAGE} (triggered by pipeline.tests-production-canary.yaml)"
  - label: ":cookie: 1h bake period before continuing promotion"
    command: "sleep 3600"
