# These pipeline steps constitute the quality gate for your service within the QA environment.
# Incorporate any necessary additional logic to validate the service's integrity. A failure in
# this pipeline build will prevent further progression to the subsequent stage.

steps:
  - label: ":rocket: Run observability gates"
    trigger: "serverless-quality-gates"
    build:
      branch: main
      commit: HEAD
      message: "${BUILDKITE_MESSAGE}"
      env:
        TARGET_ENV: qa
        SERVICE: fleet-server
        CHECK_LOG_ERROR_RATE: true
        CHECK_CONTAINER_RESTART_COUNT: true
        CONTAINER_NAME: fleet-server
        CHECK_API_REQUEST_METRICS: true
  - label: ":rocket: Run Smoke tests"
    trigger: "fleet-smoke-tests"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        ENVIRONMENT: ${ENVIRONMENT}
  - label: ":rocket: Run Scale tests"
    trigger: "fleet-scale-tests"
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        ENVIRONMENT: ${ENVIRONMENT}

