# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
name: "fleet server package mbp"
env:
  IMAGE_UBUNTU_X86_64: "platform-ingest-fleets-ubuntu-2204-1770381074"
  IMAGE_UBUNTU_ARM_64: "platform-ingest-fleet-server-ubuntu-2204-aarch64-1770381074"

# This section is used to define the plugins that will be used in the pipeline.
# See https://buildkite.com/docs/pipelines/integrations/plugins/using#using-yaml-anchors-with-plugins
common:
  - oidc_plugin: &oidc_plugin
      # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/fleet-server/01-gcp-buildkite-oidc.tf
      # This plugin authenticates to Google Cloud using the OIDC token.
      elastic/oblt-google-auth#v1.2.0:
        lifetime: 10800 # seconds
        project-id: "elastic-observability-ci"
        project-number: "911195782929"
  - dockerhub_login_plugin: &dockerhub_login_plugin
      elastic/vault-docker-login#v0.6.0:
        secret_path: 'kv/ci-shared/observability-github-secrets/shared/docker/dockerhub/observabilityrobots'
  - docker_elastic_login_plugin: &docker_elastic_login_plugin
      elastic/vault-docker-login#v0.6.0:
        secret_path: 'kv/ci-shared/platform-ingest/elastic_docker_registry'

steps:
  - label: "Package x86_64 snapshot"
    # skip building + packaging snapshot for pre-releases (flagged by a non-empty VERSION_QUALIFIER env var/BK param)
    # as prereleases are only intended to be used with staging; details in https://github.com/elastic/ingest-dev/issues/4855
    if: "build.env('VERSION_QUALIFIER') == null"
    key: "package-x86-64-snapshot"
    command: ".buildkite/scripts/package.sh snapshot"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "c2-standard-16"
    artifact_paths:
      - build/distributions/**
    plugins:
      - *oidc_plugin

  - label: "Package x86_64 staging"
    key: "package-x86-64-staging"
    command: |
      source .buildkite/scripts/version_qualifier.sh
      .buildkite/scripts/package.sh staging
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "c2-standard-16"
    artifact_paths:
      - build/distributions/**
    plugins:
      - *oidc_plugin
      - *dockerhub_login_plugin

  - label: "Package FIPS x86_64 snapshot"
    if: "build.env('VERSION_QUALIFIER') == null"
    key: "package-fips-x86-64-snapshot"
    command: ".buildkite/scripts/package.sh snapshot"
    env:
      FIPS: "true"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "c2-standard-16"
    artifact_paths:
      - build/distributions/**
    plugins:
      - *oidc_plugin
      - *docker_elastic_login_plugin

  - label: "Package FIPS x86_64 staging"
    key: "package-fips-x86-64-staging"
    command: |
      source .buildkite/scripts/version_qualifier.sh
      .buildkite/scripts/package.sh staging
    env:
      FIPS: "true"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "c2-standard-16"
    artifact_paths:
      - build/distributions/**
    plugins:
      - *oidc_plugin
      - *docker_elastic_login_plugin

  - label: "Package aarch64 snapshot"
    if: "build.env('VERSION_QUALIFIER') == null"
    key: "package-arm-snapshot"
    command: ".buildkite/scripts/package.sh snapshot"
    agents:
      provider: "aws"
      image: "${IMAGE_UBUNTU_ARM_64}"
      instanceType: "t4g.2xlarge"
    artifact_paths:
      - build/distributions/**
    plugins:
      - *oidc_plugin
      - *dockerhub_login_plugin

  - label: "Package aarch64 staging"
    key: "package-arm-staging"
    command: |
      source .buildkite/scripts/version_qualifier.sh
      .buildkite/scripts/package.sh staging
    agents:
      provider: "aws"
      image: "${IMAGE_UBUNTU_ARM_64}"
      instanceType: "t4g.2xlarge"
    artifact_paths:
      - build/distributions/**
    plugins:
      - *oidc_plugin
      - *dockerhub_login_plugin

  - label: "Package FIPS aarch64 snapshot"
    if: "build.env('VERSION_QUALIFIER') == null"
    key: "package-fips-arm-snapshot"
    command: ".buildkite/scripts/package.sh snapshot"
    env:
      FIPS: "true"
    agents:
      provider: "aws"
      image: "${IMAGE_UBUNTU_ARM_64}"
      instanceType: "t4g.2xlarge"
    artifact_paths:
      - build/distributions/**
    plugins:
      - *oidc_plugin
      - *docker_elastic_login_plugin

  - label: "Package FIPS aarch64 staging"
    key: "package-fips-arm-staging"
    command: |
      source .buildkite/scripts/version_qualifier.sh
      .buildkite/scripts/package.sh staging
    env:
      FIPS: "true"
    agents:
      provider: "aws"
      image: "${IMAGE_UBUNTU_ARM_64}"
      instanceType: "t4g.2xlarge"
    artifact_paths:
      - build/distributions/**
    plugins:
      - *oidc_plugin
      - *docker_elastic_login_plugin

  - label: "DRA snapshot"
    if: "${FILE_EXISTS_IN_REPO} && build.env('VERSION_QUALIFIER') == null"
    key: "dra-snapshot"
    command: ".buildkite/scripts/dra_release.sh snapshot"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "c2-standard-16"
    plugins:
      - *oidc_plugin
      - *docker_elastic_login_plugin
    depends_on:
      - step: "package-x86-64-snapshot"
        allow_failure: false
      - step: "package-fips-x86-64-snapshot"
        allow_failure: false
      - step: "package-arm-snapshot"
        allow_failure: false
      - step: "package-fips-arm-snapshot"
        allow_failure: false

  - label: "DRA release staging"
    # we don't usually build staging from the main branch, but we exceptionally allow it for prereleases
    # details in https://github.com/elastic/ingest-dev/issues/4855
    if: "${FILE_EXISTS_IN_REPO} == true && (build.env('BUILDKITE_BRANCH') != 'main' || build.env('VERSION_QUALIFIER') != null)"
    key: "dra-staging"
    command: |
      source .buildkite/scripts/version_qualifier.sh
      .buildkite/scripts/dra_release.sh staging
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "c2-standard-16"
    plugins:
      - *oidc_plugin
      - *docker_elastic_login_plugin
    depends_on:
      - step: "package-x86-64-staging"
        allow_failure: false
      - step: "package-fips-x86-64-staging"
        allow_failure: false
      - step: "package-arm-staging"
        allow_failure: false
      - step: "package-fips-arm-staging"
        allow_failure: false
