# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  DOCKER_COMPOSE_VERSION: "1.25.5"
  TERRAFORM_VERSION: "1.6.4"
  IMAGE_UBUNTU_X86_64: "platform-ingest-elastic-agent-ubuntu-2204-1776780011"
  IMAGE_UBUNTU_ARM_64: "platform-ingest-elastic-agent-ubuntu-2204-aarch64-1776780011"
  IMAGE_UBUNTU_X86_64_FIPS: "platform-ingest-fleet-server-ubuntu-2204-fips"

# This section is used to define the plugins that will be used in the pipeline.
# See https://buildkite.com/docs/pipelines/integrations/plugins/using#using-yaml-anchors-with-plugins
common:
  - test_collector_plugin: &test_collector_plugin
      test-collector#v1.11.0:
        files: "build/test-*.xml"
        format: "junit"
        branches: "main"
        debug: true
  - bk_analytics_token_plugin: &bk_analytics_token_plugin
      elastic/vault-secrets#v0.1.0:
        path: "kv/ci-shared/platform-ingest/buildkite_analytics_token"
        field: "token"
        env_var: "BUILDKITE_ANALYTICS_TOKEN"
  - docker_elastic_login_plugin: &docker_elastic_login_plugin
      elastic/vault-docker-login#v0.6.0:
        secret_path: 'kv/ci-shared/platform-ingest/elastic_docker_registry'
  - dockerhub_login_plugin: &dockerhub_login_plugin
      elastic/vault-docker-login#v0.6.0:
        secret_path: 'kv/ci-shared/observability-github-secrets/shared/docker/dockerhub/observabilityrobots'
  # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/fleet-server/01-gcp-buildkite-oidc.tf
  # This plugin authenticates to Google Cloud using the OIDC token.
  - oidc_plugin: &oidc_plugin
      elastic/oblt-google-auth#v1.2.0:
        lifetime: 10800 # seconds
        project-id: "elastic-observability-ci"
        project-number: "911195782929"

steps:

  - trigger: "fleet-server-package-mbp"
    label: ":esbuild: Downstream - Package"
    key: "downstream-package"
    build:
      branch: "${BUILDKITE_BRANCH}"
      commit: "${BUILDKITE_COMMIT}"
