#!/bin/bash

set -euo pipefail

GITHUB_TOKEN_VAULT_PATH="kv/ci-shared/platform-ingest/github_token"

checkout_merge() {
    local target_branch=$1
    local pr_commit=$2
    local merge_branch=$3

    if [[ -z "${target_branch}" ]]; then
        echo "No pull request target branch"
        exit 1
    fi

    git fetch -v origin "${target_branch}"
    git checkout FETCH_HEAD
    echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"

    # create temporal branch to merge the PR with the target branch
    git checkout -b ${merge_branch}
    echo "New branch created: $(git rev-parse --abbrev-ref HEAD)"

    # set author identity so it can be run git merge
    git config user.name "github-merged-pr-post-checkout"
    git config user.email "auto-merge@buildkite"

    git merge --no-edit "${BUILDKITE_COMMIT}" || {
        local merge_result=$?
        echo "Merge failed: ${merge_result}"
        git merge --abort
        exit ${merge_result}
    }
}

retry() {
    local retries=$1
    shift

    local count=0
    until "$@"; do
        exit=$?
        wait=$((2 ** count))
        count=$((count + 1))
        if [ $count -lt "$retries" ]; then
            >&2 echo "Retry $count/$retries exited $exit, retrying in $wait seconds..."
            sleep $wait
        else
            >&2 echo "Retry $count/$retries exited $exit, no more retries left."
            return $exit
        fi
    done
    return 0
}

GITHUB_REPO_TOKEN=$(retry 5 vault kv get -field token ${GITHUB_TOKEN_VAULT_PATH})

# Usage:
#check_if_file_exist_in_repo "infra" "main" "cd/release/release-manager/project-configs" "build.gradle"
#Returns IS_FILE_EXISTS_IN_REPO=true if file exists and IS_FILE_EXISTS_IN_REPO=false if not exists
check_if_file_exist_in_repo() {
    local repoName=${1}
    local branch=${2}
    local fileName="build.gradle"

    if [[ $branch == "main" ]]; then
        local branchName="master"
    fi

    local path_to_file="cd/release/release-manager/project-configs/${branchName}/${fileName}"
    local response=$(curl -s -u $GITHUB_REPO_TOKEN:x-oauth-basic https://api.github.com/repos/elastic/${repoName}/contents/${path_to_file}| grep -c "\"path\"\: \"${path_to_file}\"")
    if [[ ${response} -ge 1 ]]; then
        export IS_FILE_EXISTS_IN_REPO=true
    else
        export IS_FILE_EXISTS_IN_REPO=false
    fi
}

pull_request="${BUILDKITE_PULL_REQUEST:-false}"

if [[ "${pull_request}" == "false" ]]; then
    echo "Not a pull request, skipping"
    exit 0
fi

TARGET_BRANCH="${BUILDKITE_PULL_REQUEST_BASE_BRANCH:-master}"
PR_COMMIT="${BUILDKITE_COMMIT}"
PR_ID=${BUILDKITE_PULL_REQUEST}
MERGE_BRANCH="pr_merge_${PR_ID}"

checkout_merge "${TARGET_BRANCH}" "${PR_COMMIT}" "${MERGE_BRANCH}"

echo "Commit information"
git log --format=%B -n 1

# Ensure buildkite groups are rendered
echo ""

check_if_file_exist_in_repo "infra" "main" #TODO should be changed to ${BUILDKITE_BRANCH} before prod...