#!/bin/bash

set -euo pipefail

source .buildkite/scripts/common.sh

if [[ "$BUILDKITE_PIPELINE_SLUG" == "fleet-server" || "$BUILDKITE_PIPELINE_SLUG" == "fleet-server-perf-tests" ]]; then
  if [[ "$BUILDKITE_STEP_KEY" == "publish" || "$BUILDKITE_STEP_KEY" == "cloud-e2e-test" || "$BUILDKITE_STEP_KEY" == "create-image" ]]; then
    docker logout ${DOCKER_REGISTRY}
  fi
fi

if [[ "$BUILDKITE_PIPELINE_SLUG" == "fleet-server" && "$BUILDKITE_STEP_KEY" == "release-test" ]]; then
    unset GOOGLE_APPLICATION_CREDENTIALS
    cleanup
fi

if [[ "$BUILDKITE_PIPELINE_SLUG" == "fleet-server-package-mbp" ]]; then
  if [[ "$BUILDKITE_STEP_KEY" == "package-x86-64" || "$BUILDKITE_STEP_KEY" == "package-arm" || "$BUILDKITE_STEP_KEY" == "dra-snapshot" && "$BUILDKITE_STEP_KEY" == "dra-staging" ]]; then
    unset GOOGLE_APPLICATION_CREDENTIALS
    unset VAULT_ROLE_ID_SECRET
    unset VAULT_ADDR_SECRET
    unset VAULT_SECRET_ID_SECRET
    docker logout ${DOCKER_REGISTRY}
    cleanup
  fi
fi
