#!/bin/bash

set -euo pipefail

source .buildkite/scripts/common.sh

DOCKER_REGISTRY_SECRET_PATH="kv/ci-shared/platform-ingest/docker_registry_prod"
DOCKER_REGISTRY="docker.elastic.co"
export DOCKER_REGISTRY="${DOCKER_REGISTRY}"
EC_KEY_SECRET_PATH='kv/ci-shared/platform-ingest/platform-ingest-ec-prod'

if [[ "$BUILDKITE_STEP_KEY" == "publish" || "$BUILDKITE_STEP_KEY" == "cloud-e2e-test" ]]; then
  export DOCKER_USERNAME_SECRET=$(retry 5 vault kv get -field user "${DOCKER_REGISTRY_SECRET_PATH}")
  export DOCKER_PASSWORD_SECRET=$(retry 5 vault kv get -field password "${DOCKER_REGISTRY_SECRET_PATH}")
  docker login -u "${DOCKER_USERNAME_SECRET}" -p "${DOCKER_PASSWORD_SECRET}" "${DOCKER_REGISTRY}" 2>/dev/null
fi

if [[ "$BUILDKITE_STEP_KEY" == "cloud-e2e-test" ]]; then
  export EC_API_KEY_SECRET=$(retry 5 vault kv get -field apiKey "${EC_KEY_SECRET_PATH}")
  # Environment variables required by the Elastic Cloud service deployer
  export EC_API_KEY=${EC_API_KEY_SECRET}
fi

#TEST SECTION
if [[ "$BUILDKITE_STEP_KEY" == "check" ]]; then
  TESTVAR1_SECRET="MY$UpeRPa$$W0RD"
  export TESTVAR1=${TESTVAR1_SECRET}
  echo ${TESTVAR1}
  echo ${TESTVAR1_SECRET}

  export TESTVAR2_SECRET="MY_NOT_$UpeRPa$$W0RD"
  export TESTVAR2=${TESTVAR2_SECRET}
  echo ${TESTVAR2}
  echo ${TESTVAR2_SECRET}
fi