// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by @aleksmaus schema-generate quick&dirty mod for ES mappings. DO NOT EDIT.

package esboot

const (

	// Action An Elastic Agent action
	kMappingAction = `{
	"properties": {
		"agents": {
			"type": "keyword"
		},
		"data": {
			"enabled" : false,
			"type": "object"
		},
		"expiration": {
			"type": "date"
		},
		"id": {
			"type": "keyword"
		},
		"input_id": {
			"type": "keyword"
		},
		"@timestamp": {
			"type": "date"
		},
		"type": {
			"type": "keyword"
		}		
	}
}`

	// ActionResult An Elastic Agent action results
	kMappingActionResult = `{
	"properties": {
		"action_id": {
			"type": "keyword"
		},
		"agent_id": {
			"type": "keyword"
		},
		"data": {
			"enabled" : false,
			"type": "object"
		},
		"error": {
			"type": "keyword"
		},
		"@timestamp": {
			"type": "date"
		}		
	}
}`

	// Agent An Elastic Agent that has enrolled into Fleet
	kMappingAgent = `{
	"properties": {
		"access_api_key_id": {
			"type": "integer"
		},
		"agent": {
			"properties": {
				"id": {
					"type": "keyword"
				},
				"version": {
					"type": "keyword"
				}				
			}
		},
		"default_api_key": {
			"type": "keyword"
		},
		"default_api_key_id": {
			"type": "integer"
		},
		"enrolled_at": {
			"type": "date"
		},
		"local_metadata": {
			"enabled" : false,
			"type": "object"
		},
		"policy_id": {
			"type": "keyword"
		},
		"policy_revision": {
			"type": "integer"
		},
		"unenrolled_at": {
			"type": "date"
		},
		"unenrollment_started_at": {
			"type": "date"
		},
		"updated_at": {
			"type": "date"
		},
		"upgrade_started_at": {
			"type": "date"
		},
		"upgraded_at": {
			"type": "date"
		}		
	}
}`

	// AgentMetadata An Elastic Agent metadata
	kMappingAgentMetadata = `{
	"properties": {
		"id": {
			"type": "keyword"
		},
		"version": {
			"type": "keyword"
		}		
	}
}`

	// Data The opaque action payload.
	kMappingData = `{
	"properties": {
		
	}
}`

	// HostMetadata The host metadata for the Elastic Agent
	kMappingHostMetadata = `{
	"properties": {
		"architecture": {
			"type": "keyword"
		},
		"id": {
			"type": "keyword"
		},
		"ip": {
			"type": "keyword"
		},
		"name": {
			"type": "keyword"
		}		
	}
}`

	// LocalMetadata Local metadata information for the Elastic Agent
	kMappingLocalMetadata = `{
	"properties": {
		
	}
}`

	// Policy A policy that an Elastic Agent is attached to
	kMappingPolicy = `{
	"properties": {
		"coordinator_idx": {
			"type": "integer"
		},
		"data": {
			"type": "keyword"
		},
		"default_fleet_server": {
			"type": "boolean"
		},
		"policy_id": {
			"type": "keyword"
		},
		"revision_idx": {
			"type": "integer"
		},
		"@timestamp": {
			"type": "date"
		}		
	}
}`

	// PolicyLeader The current leader Fleet Server for a policy
	kMappingPolicyLeader = `{
	"properties": {
		"server": {
			"properties": {
				"id": {
					"type": "keyword"
				},
				"version": {
					"type": "keyword"
				}				
			}
		},
		"@timestamp": {
			"type": "date"
		}		
	}
}`

	// Server A Fleet Server
	kMappingServer = `{
	"properties": {
		"agent": {
			"properties": {
				"id": {
					"type": "keyword"
				},
				"version": {
					"type": "keyword"
				}				
			}
		},
		"host": {
			"properties": {
				"architecture": {
					"type": "keyword"
				},
				"id": {
					"type": "keyword"
				},
				"ip": {
					"type": "keyword"
				},
				"name": {
					"type": "keyword"
				}				
			}
		},
		"server": {
			"properties": {
				"id": {
					"type": "keyword"
				},
				"version": {
					"type": "keyword"
				}				
			}
		}		
	}
}`

	// ServerMetadata A Fleet Server metadata
	kMappingServerMetadata = `{
	"properties": {
		"id": {
			"type": "keyword"
		},
		"version": {
			"type": "keyword"
		}		
	}
}`
)
