---
name: bump-elastic-stack-snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1-5'

permissions:
  contents: read

env:
  JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  filter:
    runs-on: ubuntu-slim
    timeout-minutes: 1
    outputs:
      matrix: ${{ steps.generator.outputs.matrix }}
    steps:
      - id: generator
        uses: elastic/oblt-actions/elastic/active-branches@v1

  bump-elastic-stack:
    runs-on: ubuntu-latest
    needs: [filter]
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.filter.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v7

      - name: Install Updatecli in the runner
        uses: elastic/oblt-actions/updatecli/run@v1
        with:
          command: apply --config .ci/bump-elastic-stack-snapshot.yml
        env:
          BRANCH: ${{ matrix.branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ failure()  }}
        uses: elastic/oblt-actions/slack/send@v1
        id: slack
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#fleet-notifications"
          message: ":traffic_cone: updatecli failed for `${{ github.repository }}@${{ github.ref_name }}`, `@fleet_team` please look what's going on <${{ env.JOB_URL }}|here>"
